info:
  app:
    name: 认证服务UI
    description: 所有服务的入口
    version: 1.0.0.100
    #此ui依赖的service的服务名称，用于在@FeignClient中
    service:
      name: authentication-service
      #就是service的server.servlet.context-path
      prefix: "/authentication-service"
server:
  port: 9990
  servlet:
    context-path: "/authentication-ui"

spring:
  application:
    name: authentication-ui
  profiles:
    active: dev
  redis:
    jedis:
      pool:
        #配置连接池属性
        max-active: 5
        min-idle: 5
        max-idle: 5
        max-wait: 5
    #配置redis服务器属性
    database: 1
    host: 192.168.223.129
    port: 6379
    #password: bomc
    #redis连接超时时间，单位毫秒
    timeout: 2000
  activemq:
    broker-url: tcp://192.168.223.129:61616

eureka:
  client:
    service-url:
      #defaultZone: http://192.168.1.105:8761/eureka/
      defaultZone: http://192.168.223.129:8761/eureka/
  instance:
    ip-address: 192.168.223.1


#多租户相关
multiple-tenant:
  tenant: tenant1
  weight: 2
  label-and: aa,bb
  label-or: ee

