info:
  app:
    name: authentication-service-name
    description: 认证service-des
    version: 1.0.0.100

server:
#  port: 9994
#  port: 9993
#  port: 9992
  port: 9991
  servlet:
    context-path: "/authentication-service"

spring:
  application:
    name: authentication-service
  profiles:
    active: dev
  datasource:
    druid:
      #flyway使用这个参数,mysql/oracle
      db-type: mysql

      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.223.129:3306/milepost_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
      username: root
      #password: admin123
      password: ENC(tXVsX2fiUQfrNM9Gqey3pmRiLgw+Znp/ISEaZCOMDo0=)

      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #和上面的等价
      #max-open-prepared-statements:
      validation-query: SELECT 1 FROM DUAL
      #validation-query-timeout:
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #max-evictable-idle-time-millis:
      #配置多个英文逗号分隔
      #filters:
  redis:
    jedis:
      pool:
        #配置连接池属性
        max-active: 20
        min-idle: 10
        max-idle: 20
        max-wait: 2000
    #配置redis服务器属性
    database: 1
    host: 192.168.223.129
    port: 6379
    #password: bomc
    #redis连接超时时间，单位毫秒
    timeout: 2000
  flyway:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://192.168.223.129:8761/eureka/
  instance:
    ip-address: 192.168.223.1

multiple-tenant:
  tenant: tenant1
  weight: 9
  label-and: aa,bb
  label-or: dd,ee,ff







