info:
  app:
    name: 认证服务Service
    description: 为业务系统服务提供单点登录功能
    version: 1.0.0.100

server:
#  port: 9994
#  port: 9993
#  port: 9992
  port: 9991
  servlet:
    context-path: "/authentication-service"

spring:
  application:
    name: authentication-service
  profiles:
    active: dev
  datasource:
    # flyway使用这个参数，多数据源不需要配置此属性，支持oracle, mysql
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.223.129:3306/milepost_auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: admin123
    # 连接池属性配置见https://github.com/brettwooldridge/HikariCP，以下几个是常用的
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
  redis:
    jedis:
      pool:
        #配置连接池属性
        max-active: 20
        min-idle: 10
        max-idle: 20
        max-wait: 2000
    #配置redis服务器属性
    database: 1
    host: 192.168.223.129
    port: 6379
    #password: bomc
    #redis连接超时时间，单位毫秒
    timeout: 2000
  flyway:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://192.168.223.129:8761/eureka/
  instance:
    ip-address: 192.168.223.1

multiple-tenant:
  tenant: tenant1
  weight: 9
  label-and: aa,bb
  label-or: dd,ee,ff
feign:
  hystrix:
    enabled: true

tx-lcn:
  client:
    manager-address: 192.168.223.129:8070
