info:
  app:
    name: authentication-service-name
    description: 认证service-des
    version: 1.0.0.100

server:
#  port: 9998
#  port: 9997
#  port: 9996
  port: 9995
  servlet:
    context-path: "/authentication-service"

spring:
  application:
    name: authentication-service
  profiles:
    active: dev
  redis:
    jedis:
      pool:
        #配置连接池属性
        max-active: 20
        min-idle: 10
        max-idle: 20
        max-wait: 2000
    #配置redis服务器属性
    database: 1
    host: 192.168.223.129
    port: 6379
    #password: bomc
    #redis连接超时时间，单位毫秒
    timeout: 2000

eureka:
  client:
    serviceUrl:
      #defaultZone: http://192.168.1.105:8761/eureka/
      defaultZone: http://172.16.1.208:8761/eureka/
      #defaultZone: http://192.168.1.105:8761/eureka/
  instance:
    ip-address: 192.168.223.1
    #${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    #instance-id: xxx

#为了EurekaServer更灵敏而加的
eureka.instance.lease-renewal-interval-in-seconds: 4
eureka.instance.lease-expiration-duration-in-seconds: 7

#multiple-tenant:
#  tenant: abc
#  weight: 1
#  label-and: aa,bb
#  label-or: aa

#multiple-tenant:
#  tenant: abc
#  weight: 9
#  label-and: aa,bb

#multiple-tenant:
#  tenant: abc
#  weight: 0
#  label-and: aa,bb

multiple-tenant:
  tenant: def
  weight: 9
  label-and: aa,bb
  label-or: dd,ee,ff
